// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package itemproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Levy struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rate                 float32  `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	DisplayAmount        string   `protobuf:"bytes,5,opt,name=displayAmount,proto3" json:"displayAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Levy) Reset()         { *m = Levy{} }
func (m *Levy) String() string { return proto.CompactTextString(m) }
func (*Levy) ProtoMessage()    {}
func (*Levy) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Levy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Levy.Unmarshal(m, b)
}
func (m *Levy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Levy.Marshal(b, m, deterministic)
}
func (m *Levy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Levy.Merge(m, src)
}
func (m *Levy) XXX_Size() int {
	return xxx_messageInfo_Levy.Size(m)
}
func (m *Levy) XXX_DiscardUnknown() {
	xxx_messageInfo_Levy.DiscardUnknown(m)
}

var xxx_messageInfo_Levy proto.InternalMessageInfo

func (m *Levy) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Levy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Levy) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Levy) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Levy) GetDisplayAmount() string {
	if m != nil {
		return m.DisplayAmount
	}
	return ""
}

type CreateField struct {
	Warehouse            int32    `protobuf:"varint,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	Vendor               int32    `protobuf:"varint,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category             int32    `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	BrandName            string   `protobuf:"bytes,6,opt,name=brandName,proto3" json:"brandName,omitempty"`
	ModelNumber          string   `protobuf:"bytes,7,opt,name=modelNumber,proto3" json:"modelNumber,omitempty"`
	NetCost              float64  `protobuf:"fixed64,8,opt,name=netCost,proto3" json:"netCost,omitempty"`
	Levies               []*Levy  `protobuf:"bytes,9,rep,name=levies,proto3" json:"levies,omitempty"`
	SellingCostBeforeTax float64  `protobuf:"fixed64,10,opt,name=sellingCostBeforeTax,proto3" json:"sellingCostBeforeTax,omitempty"`
	SellingTaxRate       float32  `protobuf:"fixed32,11,opt,name=sellingTaxRate,proto3" json:"sellingTaxRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateField) Reset()         { *m = CreateField{} }
func (m *CreateField) String() string { return proto.CompactTextString(m) }
func (*CreateField) ProtoMessage()    {}
func (*CreateField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateField.Unmarshal(m, b)
}
func (m *CreateField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateField.Marshal(b, m, deterministic)
}
func (m *CreateField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateField.Merge(m, src)
}
func (m *CreateField) XXX_Size() int {
	return xxx_messageInfo_CreateField.Size(m)
}
func (m *CreateField) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateField.DiscardUnknown(m)
}

var xxx_messageInfo_CreateField proto.InternalMessageInfo

func (m *CreateField) GetWarehouse() int32 {
	if m != nil {
		return m.Warehouse
	}
	return 0
}

func (m *CreateField) GetVendor() int32 {
	if m != nil {
		return m.Vendor
	}
	return 0
}

func (m *CreateField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateField) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *CreateField) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *CreateField) GetModelNumber() string {
	if m != nil {
		return m.ModelNumber
	}
	return ""
}

func (m *CreateField) GetNetCost() float64 {
	if m != nil {
		return m.NetCost
	}
	return 0
}

func (m *CreateField) GetLevies() []*Levy {
	if m != nil {
		return m.Levies
	}
	return nil
}

func (m *CreateField) GetSellingCostBeforeTax() float64 {
	if m != nil {
		return m.SellingCostBeforeTax
	}
	return 0
}

func (m *CreateField) GetSellingTaxRate() float32 {
	if m != nil {
		return m.SellingTaxRate
	}
	return 0
}

type UpdateField struct {
	Warehouse            int32    `protobuf:"varint,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	Vendor               int32    `protobuf:"varint,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category             int32    `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	BrandName            string   `protobuf:"bytes,6,opt,name=brandName,proto3" json:"brandName,omitempty"`
	ModelNumber          string   `protobuf:"bytes,7,opt,name=modelNumber,proto3" json:"modelNumber,omitempty"`
	NetCost              float64  `protobuf:"fixed64,8,opt,name=netCost,proto3" json:"netCost,omitempty"`
	Levies               []*Levy  `protobuf:"bytes,9,rep,name=levies,proto3" json:"levies,omitempty"`
	SellingCostBeforeTax float64  `protobuf:"fixed64,10,opt,name=sellingCostBeforeTax,proto3" json:"sellingCostBeforeTax,omitempty"`
	SellingTaxRate       float32  `protobuf:"fixed32,11,opt,name=sellingTaxRate,proto3" json:"sellingTaxRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateField) Reset()         { *m = UpdateField{} }
func (m *UpdateField) String() string { return proto.CompactTextString(m) }
func (*UpdateField) ProtoMessage()    {}
func (*UpdateField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *UpdateField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateField.Unmarshal(m, b)
}
func (m *UpdateField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateField.Marshal(b, m, deterministic)
}
func (m *UpdateField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateField.Merge(m, src)
}
func (m *UpdateField) XXX_Size() int {
	return xxx_messageInfo_UpdateField.Size(m)
}
func (m *UpdateField) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateField.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateField proto.InternalMessageInfo

func (m *UpdateField) GetWarehouse() int32 {
	if m != nil {
		return m.Warehouse
	}
	return 0
}

func (m *UpdateField) GetVendor() int32 {
	if m != nil {
		return m.Vendor
	}
	return 0
}

func (m *UpdateField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateField) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *UpdateField) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *UpdateField) GetModelNumber() string {
	if m != nil {
		return m.ModelNumber
	}
	return ""
}

func (m *UpdateField) GetNetCost() float64 {
	if m != nil {
		return m.NetCost
	}
	return 0
}

func (m *UpdateField) GetLevies() []*Levy {
	if m != nil {
		return m.Levies
	}
	return nil
}

func (m *UpdateField) GetSellingCostBeforeTax() float64 {
	if m != nil {
		return m.SellingCostBeforeTax
	}
	return 0
}

func (m *UpdateField) GetSellingTaxRate() float32 {
	if m != nil {
		return m.SellingTaxRate
	}
	return 0
}

type RawRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RawRequest) Reset()         { *m = RawRequest{} }
func (m *RawRequest) String() string { return proto.CompactTextString(m) }
func (*RawRequest) ProtoMessage()    {}
func (*RawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *RawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRequest.Unmarshal(m, b)
}
func (m *RawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRequest.Marshal(b, m, deterministic)
}
func (m *RawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRequest.Merge(m, src)
}
func (m *RawRequest) XXX_Size() int {
	return xxx_messageInfo_RawRequest.Size(m)
}
func (m *RawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawRequest proto.InternalMessageInfo

func (m *RawRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *CreateField   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetField() *CreateField {
	if m != nil {
		return m.Field
	}
	return nil
}

type UpdateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Field                *UpdateField   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetField() *UpdateField {
	if m != nil {
		return m.Field
	}
	return nil
}

type ActionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ActionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProductQuantityRequest struct {
	Header               *RequestHeader               `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32                        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *ProductQuantityRequest_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProductQuantityRequest) Reset()         { *m = ProductQuantityRequest{} }
func (m *ProductQuantityRequest) String() string { return proto.CompactTextString(m) }
func (*ProductQuantityRequest) ProtoMessage()    {}
func (*ProductQuantityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ProductQuantityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductQuantityRequest.Unmarshal(m, b)
}
func (m *ProductQuantityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductQuantityRequest.Marshal(b, m, deterministic)
}
func (m *ProductQuantityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductQuantityRequest.Merge(m, src)
}
func (m *ProductQuantityRequest) XXX_Size() int {
	return xxx_messageInfo_ProductQuantityRequest.Size(m)
}
func (m *ProductQuantityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductQuantityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductQuantityRequest proto.InternalMessageInfo

func (m *ProductQuantityRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProductQuantityRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductQuantityRequest) GetData() *ProductQuantityRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProductQuantityRequest_Data struct {
	ReservedQuantity     int32    `protobuf:"varint,1,opt,name=reservedQuantity,proto3" json:"reservedQuantity,omitempty"`
	AvailableQuantity    int32    `protobuf:"varint,2,opt,name=availableQuantity,proto3" json:"availableQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductQuantityRequest_Data) Reset()         { *m = ProductQuantityRequest_Data{} }
func (m *ProductQuantityRequest_Data) String() string { return proto.CompactTextString(m) }
func (*ProductQuantityRequest_Data) ProtoMessage()    {}
func (*ProductQuantityRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *ProductQuantityRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductQuantityRequest_Data.Unmarshal(m, b)
}
func (m *ProductQuantityRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductQuantityRequest_Data.Marshal(b, m, deterministic)
}
func (m *ProductQuantityRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductQuantityRequest_Data.Merge(m, src)
}
func (m *ProductQuantityRequest_Data) XXX_Size() int {
	return xxx_messageInfo_ProductQuantityRequest_Data.Size(m)
}
func (m *ProductQuantityRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductQuantityRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ProductQuantityRequest_Data proto.InternalMessageInfo

func (m *ProductQuantityRequest_Data) GetReservedQuantity() int32 {
	if m != nil {
		return m.ReservedQuantity
	}
	return 0
}

func (m *ProductQuantityRequest_Data) GetAvailableQuantity() int32 {
	if m != nil {
		return m.AvailableQuantity
	}
	return 0
}

type DataResponse struct {
	StatusCode           int32              `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *DataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse_Data struct {
	Id                          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WarehouseID                 int32    `protobuf:"varint,2,opt,name=warehouseID,proto3" json:"warehouseID,omitempty"`
	Warehouse                   string   `protobuf:"bytes,3,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	VendorID                    int32    `protobuf:"varint,4,opt,name=vendorID,proto3" json:"vendorID,omitempty"`
	Vendor                      string   `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	CategoryID                  int32    `protobuf:"varint,6,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Category                    string   `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Name                        string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Description                 string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	SkuNumber                   string   `protobuf:"bytes,10,opt,name=skuNumber,proto3" json:"skuNumber,omitempty"`
	BrandName                   string   `protobuf:"bytes,11,opt,name=brandName,proto3" json:"brandName,omitempty"`
	ModelNumber                 string   `protobuf:"bytes,12,opt,name=modelNumber,proto3" json:"modelNumber,omitempty"`
	NetCost                     float64  `protobuf:"fixed64,13,opt,name=netCost,proto3" json:"netCost,omitempty"`
	DisplayNetCost              string   `protobuf:"bytes,14,opt,name=displayNetCost,proto3" json:"displayNetCost,omitempty"`
	Levies                      []*Levy  `protobuf:"bytes,15,rep,name=levies,proto3" json:"levies,omitempty"`
	AvailableQuantity           int32    `protobuf:"varint,16,opt,name=availableQuantity,proto3" json:"availableQuantity,omitempty"`
	ReservedQuantity            int32    `protobuf:"varint,17,opt,name=reservedQuantity,proto3" json:"reservedQuantity,omitempty"`
	TotalCost                   float64  `protobuf:"fixed64,18,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	DisplayTotalCost            string   `protobuf:"bytes,19,opt,name=displayTotalCost,proto3" json:"displayTotalCost,omitempty"`
	SellingCostBeforeTax        float64  `protobuf:"fixed64,20,opt,name=sellingCostBeforeTax,proto3" json:"sellingCostBeforeTax,omitempty"`
	DisplaySellingCostBeforeTax string   `protobuf:"bytes,21,opt,name=displaySellingCostBeforeTax,proto3" json:"displaySellingCostBeforeTax,omitempty"`
	SellingTaxRate              float32  `protobuf:"fixed32,22,opt,name=sellingTaxRate,proto3" json:"sellingTaxRate,omitempty"`
	DisplaySellingTaxRate       string   `protobuf:"bytes,23,opt,name=displaySellingTaxRate,proto3" json:"displaySellingTaxRate,omitempty"`
	SellingTaxAmount            float64  `protobuf:"fixed64,24,opt,name=sellingTaxAmount,proto3" json:"sellingTaxAmount,omitempty"`
	DisplaySellingTaxAmount     string   `protobuf:"bytes,25,opt,name=displaySellingTaxAmount,proto3" json:"displaySellingTaxAmount,omitempty"`
	SellingCostAfterTax         float64  `protobuf:"fixed64,26,opt,name=sellingCostAfterTax,proto3" json:"sellingCostAfterTax,omitempty"`
	DisplaySellingCostAfterTax  string   `protobuf:"bytes,27,opt,name=displaySellingCostAfterTax,proto3" json:"displaySellingCostAfterTax,omitempty"`
	CreatedDate                 string   `protobuf:"bytes,28,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	CreatedBy                   string   `protobuf:"bytes,29,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	LastModifiedBy              string   `protobuf:"bytes,30,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	LastModifiedDate            string   `protobuf:"bytes,31,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	RecordState                 string   `protobuf:"bytes,32,opt,name=recordState,proto3" json:"recordState,omitempty"`
	ReferencedBy                int64    `protobuf:"varint,33,opt,name=referencedBy,proto3" json:"referencedBy,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *DataResponse_Data) Reset()         { *m = DataResponse_Data{} }
func (m *DataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DataResponse_Data) ProtoMessage()    {}
func (*DataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 0}
}

func (m *DataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse_Data.Unmarshal(m, b)
}
func (m *DataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse_Data.Marshal(b, m, deterministic)
}
func (m *DataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse_Data.Merge(m, src)
}
func (m *DataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DataResponse_Data.Size(m)
}
func (m *DataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse_Data proto.InternalMessageInfo

func (m *DataResponse_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResponse_Data) GetWarehouseID() int32 {
	if m != nil {
		return m.WarehouseID
	}
	return 0
}

func (m *DataResponse_Data) GetWarehouse() string {
	if m != nil {
		return m.Warehouse
	}
	return ""
}

func (m *DataResponse_Data) GetVendorID() int32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *DataResponse_Data) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DataResponse_Data) GetCategoryID() int32 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *DataResponse_Data) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DataResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataResponse_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataResponse_Data) GetSkuNumber() string {
	if m != nil {
		return m.SkuNumber
	}
	return ""
}

func (m *DataResponse_Data) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *DataResponse_Data) GetModelNumber() string {
	if m != nil {
		return m.ModelNumber
	}
	return ""
}

func (m *DataResponse_Data) GetNetCost() float64 {
	if m != nil {
		return m.NetCost
	}
	return 0
}

func (m *DataResponse_Data) GetDisplayNetCost() string {
	if m != nil {
		return m.DisplayNetCost
	}
	return ""
}

func (m *DataResponse_Data) GetLevies() []*Levy {
	if m != nil {
		return m.Levies
	}
	return nil
}

func (m *DataResponse_Data) GetAvailableQuantity() int32 {
	if m != nil {
		return m.AvailableQuantity
	}
	return 0
}

func (m *DataResponse_Data) GetReservedQuantity() int32 {
	if m != nil {
		return m.ReservedQuantity
	}
	return 0
}

func (m *DataResponse_Data) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *DataResponse_Data) GetDisplayTotalCost() string {
	if m != nil {
		return m.DisplayTotalCost
	}
	return ""
}

func (m *DataResponse_Data) GetSellingCostBeforeTax() float64 {
	if m != nil {
		return m.SellingCostBeforeTax
	}
	return 0
}

func (m *DataResponse_Data) GetDisplaySellingCostBeforeTax() string {
	if m != nil {
		return m.DisplaySellingCostBeforeTax
	}
	return ""
}

func (m *DataResponse_Data) GetSellingTaxRate() float32 {
	if m != nil {
		return m.SellingTaxRate
	}
	return 0
}

func (m *DataResponse_Data) GetDisplaySellingTaxRate() string {
	if m != nil {
		return m.DisplaySellingTaxRate
	}
	return ""
}

func (m *DataResponse_Data) GetSellingTaxAmount() float64 {
	if m != nil {
		return m.SellingTaxAmount
	}
	return 0
}

func (m *DataResponse_Data) GetDisplaySellingTaxAmount() string {
	if m != nil {
		return m.DisplaySellingTaxAmount
	}
	return ""
}

func (m *DataResponse_Data) GetSellingCostAfterTax() float64 {
	if m != nil {
		return m.SellingCostAfterTax
	}
	return 0
}

func (m *DataResponse_Data) GetDisplaySellingCostAfterTax() string {
	if m != nil {
		return m.DisplaySellingCostAfterTax
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *DataResponse_Data) GetRecordState() string {
	if m != nil {
		return m.RecordState
	}
	return ""
}

func (m *DataResponse_Data) GetReferencedBy() int64 {
	if m != nil {
		return m.ReferencedBy
	}
	return 0
}

type RawResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RawResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RawResponse) Reset()         { *m = RawResponse{} }
func (m *RawResponse) String() string { return proto.CompactTextString(m) }
func (*RawResponse) ProtoMessage()    {}
func (*RawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *RawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse.Unmarshal(m, b)
}
func (m *RawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse.Marshal(b, m, deterministic)
}
func (m *RawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse.Merge(m, src)
}
func (m *RawResponse) XXX_Size() int {
	return xxx_messageInfo_RawResponse.Size(m)
}
func (m *RawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse proto.InternalMessageInfo

func (m *RawResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RawResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RawResponse) GetData() *RawResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RawResponse_Data struct {
	LevyTypes            []*Levy  `protobuf:"bytes,1,rep,name=levyTypes,proto3" json:"levyTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawResponse_Data) Reset()         { *m = RawResponse_Data{} }
func (m *RawResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RawResponse_Data) ProtoMessage()    {}
func (*RawResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11, 0}
}

func (m *RawResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse_Data.Unmarshal(m, b)
}
func (m *RawResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse_Data.Marshal(b, m, deterministic)
}
func (m *RawResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse_Data.Merge(m, src)
}
func (m *RawResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RawResponse_Data.Size(m)
}
func (m *RawResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse_Data proto.InternalMessageInfo

func (m *RawResponse_Data) GetLevyTypes() []*Levy {
	if m != nil {
		return m.LevyTypes
	}
	return nil
}

type SimpleResponse struct {
	StatusCode           int32                `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SimpleResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SimpleResponse) GetData() *SimpleResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleResponse_Data struct {
	ReservedQuantity     int32    `protobuf:"varint,1,opt,name=reservedQuantity,proto3" json:"reservedQuantity,omitempty"`
	AvailableQuantity    int32    `protobuf:"varint,2,opt,name=availableQuantity,proto3" json:"availableQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse_Data) Reset()         { *m = SimpleResponse_Data{} }
func (m *SimpleResponse_Data) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse_Data) ProtoMessage()    {}
func (*SimpleResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 0}
}

func (m *SimpleResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse_Data.Unmarshal(m, b)
}
func (m *SimpleResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse_Data.Marshal(b, m, deterministic)
}
func (m *SimpleResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse_Data.Merge(m, src)
}
func (m *SimpleResponse_Data) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse_Data.Size(m)
}
func (m *SimpleResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse_Data proto.InternalMessageInfo

func (m *SimpleResponse_Data) GetReservedQuantity() int32 {
	if m != nil {
		return m.ReservedQuantity
	}
	return 0
}

func (m *SimpleResponse_Data) GetAvailableQuantity() int32 {
	if m != nil {
		return m.AvailableQuantity
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "itemproto.RequestHeader")
	proto.RegisterType((*Levy)(nil), "itemproto.Levy")
	proto.RegisterType((*CreateField)(nil), "itemproto.CreateField")
	proto.RegisterType((*UpdateField)(nil), "itemproto.UpdateField")
	proto.RegisterType((*RawRequest)(nil), "itemproto.RawRequest")
	proto.RegisterType((*GetRequest)(nil), "itemproto.GetRequest")
	proto.RegisterType((*CreateRequest)(nil), "itemproto.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "itemproto.UpdateRequest")
	proto.RegisterType((*ActionRequest)(nil), "itemproto.ActionRequest")
	proto.RegisterType((*ProductQuantityRequest)(nil), "itemproto.ProductQuantityRequest")
	proto.RegisterType((*ProductQuantityRequest_Data)(nil), "itemproto.ProductQuantityRequest.Data")
	proto.RegisterType((*DataResponse)(nil), "itemproto.DataResponse")
	proto.RegisterType((*DataResponse_Data)(nil), "itemproto.DataResponse.Data")
	proto.RegisterType((*RawResponse)(nil), "itemproto.RawResponse")
	proto.RegisterType((*RawResponse_Data)(nil), "itemproto.RawResponse.Data")
	proto.RegisterType((*SimpleResponse)(nil), "itemproto.SimpleResponse")
	proto.RegisterType((*SimpleResponse_Data)(nil), "itemproto.SimpleResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0xf7, 0xaf, 0xf1, 0xd9, 0x6c, 0xda, 0x4e, 0xf3, 0xe3, 0x6e, 0x42, 0xd8, 0x5a, 0x10,
	0x22, 0x54, 0x42, 0xb4, 0xb4, 0x12, 0xa2, 0x52, 0x45, 0x9a, 0x88, 0x12, 0x09, 0x22, 0x70, 0xd2,
	0x7b, 0x26, 0xeb, 0x93, 0xd4, 0xd4, 0x6b, 0x2f, 0xf6, 0xec, 0xa6, 0x2b, 0x21, 0x21, 0x9e, 0x88,
	0x57, 0xe2, 0x01, 0x90, 0xb8, 0xe1, 0x82, 0x4b, 0x34, 0x67, 0xc6, 0xf6, 0x38, 0xeb, 0xdd, 0x4a,
	0x25, 0xea, 0x55, 0xef, 0x3c, 0xdf, 0x9c, 0x7f, 0x9f, 0xf3, 0x9d, 0x81, 0x4e, 0x8a, 0xc9, 0x24,
	0x18, 0xe0, 0xde, 0x28, 0x89, 0x45, 0xcc, 0xec, 0x40, 0xe0, 0x90, 0x3e, 0xdd, 0x8f, 0xa1, 0xe3,
	0xe1, 0x2f, 0x63, 0x4c, 0xc5, 0xb7, 0xc8, 0x7d, 0x4c, 0xd8, 0x2a, 0x34, 0x45, 0xfc, 0x0a, 0x23,
	0xc7, 0xea, 0x59, 0xbb, 0xb6, 0xa7, 0x0e, 0xee, 0xaf, 0xd0, 0xf8, 0x0e, 0x27, 0x53, 0xb6, 0x02,
	0xb5, 0xc0, 0xa7, 0xab, 0xa6, 0x57, 0x0b, 0x7c, 0xc6, 0xa0, 0x11, 0xf1, 0x21, 0x3a, 0x35, 0x12,
	0xa6, 0x6f, 0x89, 0x25, 0x5c, 0xa0, 0x53, 0xef, 0x59, 0xbb, 0x35, 0x8f, 0xbe, 0xd9, 0x3a, 0xb4,
	0xf8, 0x30, 0x1e, 0x47, 0xc2, 0x69, 0xf4, 0xac, 0x5d, 0xcb, 0xd3, 0x27, 0xf6, 0x11, 0x74, 0xfc,
	0x20, 0x1d, 0x85, 0x7c, 0x7a, 0xa0, 0xae, 0x9b, 0x64, 0xa8, 0x0c, 0xba, 0xff, 0xd4, 0xa0, 0x7d,
	0x98, 0x20, 0x17, 0xf8, 0x4d, 0x80, 0xa1, 0xcf, 0xb6, 0xc0, 0xbe, 0xe2, 0x09, 0xbe, 0x8c, 0xc7,
	0x29, 0xea, 0x60, 0x0a, 0x40, 0xfa, 0x9a, 0x60, 0xe4, 0xc7, 0x09, 0x45, 0xd5, 0xf4, 0xf4, 0x29,
	0x8f, 0xb5, 0x6e, 0xc4, 0xda, 0x83, 0xb6, 0x8f, 0xe9, 0x20, 0x09, 0x46, 0x22, 0x88, 0x23, 0x0a,
	0xce, 0xf6, 0x4c, 0x88, 0x75, 0x61, 0x69, 0xc0, 0x05, 0x5e, 0xc6, 0xc9, 0x94, 0x82, 0x6b, 0x7a,
	0xf9, 0x59, 0xc6, 0x71, 0x9e, 0xf0, 0xc8, 0x3f, 0x91, 0x66, 0x5b, 0xa4, 0x5b, 0x00, 0xd2, 0xf6,
	0x30, 0xf6, 0x31, 0x3c, 0x19, 0x0f, 0xcf, 0x31, 0x71, 0x6e, 0x29, 0xdb, 0x06, 0xc4, 0x1c, 0xb8,
	0x15, 0xa1, 0x38, 0x8c, 0x53, 0xe1, 0x2c, 0x51, 0x59, 0xb2, 0x23, 0xfb, 0x04, 0x5a, 0x21, 0x4e,
	0x02, 0x4c, 0x1d, 0xbb, 0x57, 0xdf, 0x6d, 0xf7, 0x6f, 0xef, 0xe5, 0xbf, 0x6c, 0x4f, 0xfe, 0x08,
	0x4f, 0x5f, 0xb3, 0x3e, 0xac, 0xa6, 0x18, 0x86, 0x41, 0x74, 0x29, 0xf5, 0x9e, 0xe1, 0x45, 0x9c,
	0xe0, 0x19, 0x7f, 0xed, 0x00, 0xd9, 0xab, 0xbc, 0x63, 0x3b, 0xb0, 0xa2, 0xf1, 0x33, 0xfe, 0xda,
	0x93, 0xbf, 0xaa, 0x4d, 0xbf, 0xea, 0x1a, 0x4a, 0x65, 0x7f, 0x31, 0xf2, 0xdf, 0x97, 0xfd, 0xdd,
	0x96, 0xfd, 0x29, 0x80, 0xc7, 0xaf, 0xf4, 0x54, 0xb2, 0x7d, 0x68, 0xbd, 0xa4, 0xc9, 0xa4, 0x8a,
	0xb7, 0xfb, 0x8e, 0x11, 0x52, 0x69, 0x72, 0x3d, 0x2d, 0xe7, 0x9e, 0x00, 0x3c, 0x47, 0xf1, 0xd6,
	0xfa, 0x7a, 0xc6, 0x6b, 0xd9, 0x8c, 0xbb, 0x31, 0x74, 0xd4, 0xf0, 0xbd, 0xbd, 0xc9, 0x87, 0xd0,
	0xbc, 0x90, 0x2d, 0x44, 0x56, 0xdb, 0xfd, 0x75, 0x43, 0xc1, 0x98, 0x6b, 0x4f, 0x09, 0xb9, 0xbf,
	0x41, 0x47, 0xb5, 0xdd, 0x8d, 0xe5, 0x50, 0x04, 0x50, 0x9f, 0x09, 0xc0, 0xe8, 0xf0, 0x2c, 0x00,
	0x84, 0xce, 0xc1, 0x40, 0xb6, 0xe1, 0xcd, 0x05, 0x50, 0x31, 0x05, 0xee, 0xbf, 0x16, 0xac, 0xff,
	0x90, 0xc4, 0xfe, 0x78, 0x20, 0x7e, 0x1c, 0xf3, 0x48, 0x04, 0x62, 0x7a, 0x73, 0x0e, 0xbf, 0x82,
	0x86, 0xcf, 0x05, 0xd7, 0x09, 0xef, 0x18, 0xfa, 0xd5, 0x2e, 0xf7, 0x8e, 0xb8, 0xe0, 0x1e, 0xe9,
	0x74, 0x7f, 0x82, 0x86, 0x3c, 0xb1, 0x4f, 0xe1, 0x4e, 0x82, 0x72, 0x75, 0xa0, 0x9f, 0x49, 0xeb,
	0xb9, 0x9f, 0xc1, 0xd9, 0x43, 0xb8, 0xcb, 0x27, 0x3c, 0x08, 0xf9, 0x79, 0x88, 0xb9, 0xb0, 0x0a,
	0x67, 0xf6, 0xc2, 0xfd, 0x0b, 0x60, 0x99, 0x1c, 0x62, 0x3a, 0x8a, 0xa3, 0x14, 0xd9, 0x36, 0x40,
	0x2a, 0xb8, 0x18, 0xa7, 0x87, 0xb1, 0x9f, 0x91, 0x8b, 0x81, 0xc8, 0x99, 0x1d, 0x62, 0x9a, 0xf2,
	0xcb, 0x6c, 0xd7, 0x64, 0x47, 0xb6, 0x5f, 0x4a, 0x74, 0xcb, 0x48, 0xd4, 0x74, 0x60, 0xa6, 0xf7,
	0xb7, 0xad, 0xf3, 0x2b, 0xb6, 0x99, 0x4d, 0x35, 0xeb, 0x41, 0x3b, 0xe7, 0xb3, 0xe3, 0x23, 0x1d,
	0xbd, 0x09, 0x95, 0x29, 0x50, 0xfd, 0x4b, 0x83, 0x02, 0xbb, 0xb0, 0xa4, 0x48, 0xef, 0xf8, 0x88,
	0x38, 0xad, 0xe9, 0xe5, 0x67, 0x83, 0x1e, 0xd5, 0x8a, 0xcb, 0xe8, 0x71, 0x1b, 0x20, 0x23, 0xb6,
	0xe3, 0x23, 0x62, 0xb3, 0xa6, 0x67, 0x20, 0x25, 0x22, 0x54, 0x5c, 0x56, 0x10, 0x61, 0xd6, 0x54,
	0x4b, 0xf3, 0xa9, 0xd5, 0x9e, 0xa5, 0xd6, 0x2d, 0xb0, 0xd3, 0x57, 0x63, 0x4d, 0x8f, 0xa0, 0x72,
	0xc8, 0x81, 0x32, 0xb9, 0xb6, 0xdf, 0x40, 0xae, 0xcb, 0x0b, 0xc9, 0xb5, 0x53, 0x26, 0xd7, 0x1d,
	0x58, 0xd1, 0x6b, 0xfd, 0x44, 0x0b, 0xac, 0x90, 0xfa, 0x35, 0xd4, 0x20, 0xe1, 0xdb, 0x8b, 0x49,
	0xb8, 0xb2, 0xe5, 0xee, 0xcc, 0x69, 0xb9, 0xca, 0x66, 0xbe, 0x3b, 0xa7, 0x99, 0xb7, 0xc0, 0x16,
	0xb1, 0xe0, 0x21, 0x45, 0xc9, 0x28, 0x8d, 0x02, 0x90, 0x96, 0x74, 0xc8, 0x67, 0xb9, 0xd0, 0x3d,
	0x4a, 0x65, 0x06, 0x9f, 0xbb, 0x28, 0x56, 0x17, 0x2c, 0x8a, 0xaf, 0x61, 0x53, 0xdb, 0x39, 0xad,
	0x52, 0x5d, 0x23, 0x57, 0x8b, 0x44, 0x2a, 0x56, 0xcd, 0x7a, 0xd5, 0xaa, 0x61, 0x8f, 0x60, 0xad,
	0x6c, 0x26, 0x13, 0xdf, 0x20, 0x1f, 0xd5, 0x97, 0x32, 0xff, 0xc2, 0x8e, 0x7e, 0xb7, 0x39, 0x94,
	0xcf, 0x0c, 0xce, 0xbe, 0x84, 0x8d, 0x19, 0x23, 0x5a, 0xe5, 0x3e, 0xf9, 0x98, 0x77, 0xcd, 0xf6,
	0xe1, 0x9e, 0x51, 0x9d, 0x83, 0x0b, 0x81, 0x89, 0xcc, 0xbe, 0x4b, 0x8e, 0xaa, 0xae, 0xd8, 0x53,
	0xe8, 0xce, 0x16, 0x25, 0x57, 0xdc, 0x24, 0x77, 0x0b, 0x24, 0x64, 0x73, 0x0f, 0x68, 0x1b, 0xf9,
	0x47, 0xb2, 0x06, 0x5b, 0xaa, 0xb9, 0x0d, 0x48, 0xf6, 0x85, 0x3e, 0x3e, 0x9b, 0x3a, 0x1f, 0xa8,
	0xe1, 0xc8, 0x01, 0x59, 0xf5, 0x90, 0xa7, 0xe2, 0xfb, 0xd8, 0x0f, 0x2e, 0x02, 0x12, 0xd9, 0x56,
	0x0d, 0x5e, 0x46, 0x65, 0xfd, 0x4c, 0x84, 0x9c, 0x7d, 0xa8, 0xfa, 0xe7, 0x3a, 0x2e, 0x63, 0x4a,
	0x70, 0x10, 0x27, 0xfe, 0xa9, 0x90, 0x62, 0x3d, 0x15, 0x93, 0x01, 0x31, 0x17, 0x96, 0x13, 0xbc,
	0xc0, 0x04, 0xa3, 0x01, 0xf9, 0x7c, 0xd0, 0xb3, 0x76, 0xeb, 0x5e, 0x09, 0x73, 0xff, 0xb0, 0xa0,
	0x4d, 0x6f, 0x8a, 0xff, 0xcd, 0xb6, 0x9f, 0x97, 0xd8, 0x76, 0xd3, 0x5c, 0x4b, 0x85, 0x7d, 0x93,
	0x6c, 0x1f, 0x6b, 0xae, 0xfd, 0x0c, 0xec, 0x10, 0x27, 0xd3, 0xb3, 0xe9, 0x08, 0x53, 0xc7, 0xaa,
	0x1e, 0xec, 0x42, 0xc2, 0xfd, 0xd3, 0x82, 0x95, 0xd3, 0x60, 0x38, 0x0a, 0xf1, 0x06, 0x82, 0xee,
	0x97, 0x82, 0xde, 0x36, 0xdc, 0x96, 0x5d, 0xbc, 0xd3, 0x1d, 0xd8, 0xff, 0xbd, 0x0e, 0x8d, 0x63,
	0x81, 0x43, 0xf6, 0x08, 0xea, 0x1e, 0xbf, 0x62, 0x6b, 0xd7, 0x8b, 0x49, 0x7b, 0xb9, 0xbb, 0x5e,
	0x5d, 0x63, 0xf6, 0x04, 0x5a, 0xea, 0xed, 0xc4, 0x9c, 0x99, 0xe7, 0x54, 0xa6, 0xbb, 0x31, 0x67,
	0x1b, 0xb2, 0xc7, 0x50, 0x7f, 0x8e, 0xa2, 0xe4, 0xb2, 0x78, 0x33, 0xce, 0x57, 0x7b, 0x02, 0x2d,
	0xf5, 0x5c, 0x2a, 0xf9, 0x2c, 0x3d, 0xd6, 0x16, 0x2a, 0xab, 0x57, 0x55, 0x49, 0xb9, 0xf4, 0xd0,
	0x9a, 0xaf, 0xfc, 0x02, 0xd6, 0x0e, 0xfc, 0x9f, 0xc7, 0xa9, 0xb8, 0xf6, 0x7a, 0x61, 0x0f, 0xde,
	0xf8, 0xb2, 0xe9, 0xde, 0x9f, 0xfb, 0xc3, 0xcf, 0x5b, 0x84, 0x7e, 0xf1, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0x47, 0xbe, 0xf3, 0x21, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemClient is the client API for Item service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemClient interface {
	Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error)
	AdjustProductQuantity(ctx context.Context, in *ProductQuantityRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type itemClient struct {
	cc *grpc.ClientConn
}

func NewItemClient(cc *grpc.ClientConn) ItemClient {
	return &itemClient{cc}
}

func (c *itemClient) Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error) {
	out := new(RawResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/Raw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) AdjustProductQuantity(ctx context.Context, in *ProductQuantityRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/itemproto.Item/AdjustProductQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServer is the server API for Item service.
type ItemServer interface {
	Raw(context.Context, *RawRequest) (*RawResponse, error)
	Create(context.Context, *CreateRequest) (*DataResponse, error)
	Get(context.Context, *GetRequest) (*DataResponse, error)
	Update(context.Context, *UpdateRequest) (*DataResponse, error)
	Action(context.Context, *ActionRequest) (*DataResponse, error)
	AdjustProductQuantity(context.Context, *ProductQuantityRequest) (*SimpleResponse, error)
}

// UnimplementedItemServer can be embedded to have forward compatible implementations.
type UnimplementedItemServer struct {
}

func (*UnimplementedItemServer) Raw(ctx context.Context, req *RawRequest) (*RawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Raw not implemented")
}
func (*UnimplementedItemServer) Create(ctx context.Context, req *CreateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedItemServer) Get(ctx context.Context, req *GetRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedItemServer) Update(ctx context.Context, req *UpdateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedItemServer) Action(ctx context.Context, req *ActionRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (*UnimplementedItemServer) AdjustProductQuantity(ctx context.Context, req *ProductQuantityRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustProductQuantity not implemented")
}

func RegisterItemServer(s *grpc.Server, srv ItemServer) {
	s.RegisterService(&_Item_serviceDesc, srv)
}

func _Item_Raw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Raw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/Raw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Raw(ctx, req.(*RawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_AdjustProductQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).AdjustProductQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemproto.Item/AdjustProductQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).AdjustProductQuantity(ctx, req.(*ProductQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Item_serviceDesc = grpc.ServiceDesc{
	ServiceName: "itemproto.Item",
	HandlerType: (*ItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Raw",
			Handler:    _Item_Raw_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Item_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Item_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Item_Update_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Item_Action_Handler,
		},
		{
			MethodName: "AdjustProductQuantity",
			Handler:    _Item_AdjustProductQuantity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
